# Generated by Django 4.2 on 2023-04-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='titles',
            new_name='title',
        ),
    ]
